# Generated by Django 4.1.2 on 2022-10-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.BooleanField(default=False),
        ),
    ]
