# Generated by Django 4.1.2 on 2022-10-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_watchlist_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.BooleanField(),
        ),
    ]
