# Generated by Django 4.1.2 on 2022-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_watchlist_id_alter_watchlist_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.BooleanField(blank=True),
        ),
    ]
