# Generated by Django 4.1.2 on 2022-10-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_watchlist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.BooleanField(null=True),
        ),
    ]
