# Generated by Django 4.1.2 on 2022-10-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_watchlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watch_list',
            new_name='watchlist',
        ),
    ]
