# Generated by Django 4.1.2 on 2022-10-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_watch_list_watchlist_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='tmdBid_id',
            new_name='tmdbId',
        ),
    ]
